### ISSUE TITLE
Placing follow up PayPal (AUTH only) order duplicate error?

### ISSUE THREAD

**Issue by JeffMash** [lat9/paypalr#28]
I am creating this issue here, but it's outlined in more detail here: https://www.zen-cart.com/showthread.php?229886-PayPal-RESTful-API-Payment-Module&p=1401920#post1401920

Maybe see if you can recreate this?

1.  Configure your module to be AUTH Only.   
2.  Place a PayPal Wallet order (not credit card).  It will show up in your PayPal account as authorized only.
3. In the ZenCart Admin --> Orders, go ahead and VOID that transaction.   You are not charged anything, and the PayPal transaction is successfully voided.
4. Now, repeat the exact same process.  Using the same ZenCart Customer account, purchase the exact same item, using PayPal Wallet.

When I try to checkout the second time, I am getting the error outlined in the forum link above.    Specifically, it's:

```
The curlPost (v2/checkout/orders/0K792404TN0597925/confirm-payment-source) request was unsuccessful.
{
    "errNum": 422,
    "errMsg": "An interface error (422) was returned from PayPal.",
    "curlErrno": 0,
    "name": "UNPROCESSABLE_ENTITY",
    "message": "The requested action could not be performed, semantically incorrect, or failed business validation.",
    "details": [
        {
            "issue": "ORDER_ALREADY_AUTHORIZED",
            "description": "Order already authorized.If 'intent=AUTHORIZE' only one authorization per order is allowed."
        }
    ],
    "debug_id": "81bd08dcd3053"
}
```

As you can see, it seems to indicate that the AUTH order already exists, but at this point, the order has been voided and confirmed voided in PayPal, so I don't know why the module is still seeing it as ORDER_ALREADY_AUTHORIZED.

I don't know if this something wrong on MY end (quite possible), or if it's related to the module being AUTH only on a PayPal Wallet transaction.

1.  The order DID go through successfully the first time.
2.  I only noticed a problem when I tried to do it a second time.
3.  I have since removed the Restful module and put back the original paypal modules.
4.  I am running ZC 1.5.8a, Bootstrap 3.7.0, and OPC 2.4.6

**Comment by lat9** [comment]
Was the repeated order placed within the same customer-session?  That is, did you re-login to the customer's account to place that order-repeat?

**Comment by lat9** [comment]
@brittainmark, would you see if this change corrects the issue you posted in the Zen Cart forum?

**Comment by brittainmark** [comment]
I'll look tomorrow. Mine was not auth only. I used the same login.

**Comment by brittainmark** [comment]
I have retested and this works for final payment, auth only and credit card all work fine thanks.

**Comment by lat9** [comment]
Thanks for the verification, @brittainmark!
