### ISSUE TITLE
MISSING_REQUIRED_PARAMETER returned when customer's first/last contains multi-byte characters

### ISSUE THREAD

**Issue by lat9** [lat9/paypalr#29]
The first 3 characters of the customer's first/last names are used for both the debug-trace log file's name and as the `invoice_id` sent to PayPal.  If those characters contain multi-byte characters, e.g. a first/last of `Juan/Niña`, the use of `substr` to gather those characters results in invalid utf8 characters, which results in a 400-status return from PayPal along with an `MISSING_REQUIRED_PARAMETER` reason-code.

This can be corrected by using multi-byte-safe functions (if present in the site's PHP build).

**Comment by drbyte** [comment]
Does the fix still "use" the mb char if found? Is there any value in converting those to non-mb chars when using them in the filename and the invoice number?

**Comment by lat9** [comment]
> Does the fix still "use" the mb char if found? Is there any value in converting those to non-mb chars when using them in the filename and the invoice number?

No, the invoice-id and filename 'customer-name' elements are limited to alphanumeric for simplicity.
