### ISSUE TITLE
Invalid Fatal error during admin processing

### ISSUE THREAD

**Issue by lat9** [lat9/paypalr#36]
Having a mare of a day. been at this  most of today and cannot solve this issue with a base build, paypal restfull and bootstrap.
```
[17-Aug-2024 15:35:15 UTC] Request URI: /test/toasT-mZz-Coach/index.php?cmd=modules&set=payment, IP address: 127.0.0.1

--> PHP Fatal error: Uncaught Error: Class "currencies" not found in /home/lotus/public_html/innerlightcrystals/test/includes/modules/payment/paypalr.php:350
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/test/ADMIN/modules.php(173): paypalr->__construct()
#1 /home/lotus/public_html/innerlightcrystals/test/ADMIN/index.php(16): require('...')
#2 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/test/includes/modules/payment/paypalr.php on line 350.
```

Currencies class does not seem to be loaded. was ok until i tried to enable paypal restful?
Any ideas what i have screwed up?

_Originally posted by @brittainmark in https://github.com/lat9/paypalr/issues/33#issuecomment-2294894312_

**Comment by lat9** [comment]
Issue introduced in v1.0.2 via update for #17.  The payment-module's constructor needs to return after it validates the configuration when running in the admin.

**Comment by lat9** [comment]
@brittainmark, please verify that the correction just posted corrects this issue.

**Comment by brittainmark** [comment]
Yes this is fixed. Sorry for the delay. time difference.
